apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  type: {{ .Values.kibana.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.kibana.service.port }}
      targetPort: 5601
      {{- if eq .Values.kibana.service.type "NodePort" }}
      nodePort: {{ .Values.kibana.service.nodePort }}
      {{- end }}
  selector:
    app: kibana
