apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  type: {{ .Values.logstash.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.logstash.service.port }}
      targetPort: 5044
  selector:
    app: logstash
