apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.nginx.service.port }}
      targetPort: 80
  type: LoadBalancer
  selector:
    app: nginx
