apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: bitnami
  pass_credentials_all: false
  password: ""
  url: https://charts.bitnami.com/bitnami
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: elastic
  pass_credentials_all: false
  password: ""
  url: https://helm.elastic.co
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: nfs-subdir-external-provisioner
  pass_credentials_all: false
  password: ""
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
  username: ""
